name: CI

on:
  push:
    branches: [main]
    tags: [v*]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: ${{ matrix.platform }} (${{ matrix.python-version }})
    runs-on: ${{ matrix.platform }}
    env:
      UV_FROZEN: 1
      UV_PYTHON: ${{ matrix.python-version }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.14"]
        platform: [windows-latest, ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - uses: extractions/setup-just@v4
      - uses: astral-sh/setup-uv@v10.2.0
        with:
          enable-cache: true
      - uses: TheMrMilchmann/setup-msvc-dev@v4
        if: matrix.platform == 'windows-latest'
        with:
          arch: x64

      - name: install
        # install with coverage=true
        run: just install true

      - name: test
        run: uv run --no-sync pytest --color=yes -v --cov --cov-report=xml

      - name: cpp-coverage
        run: uv run --no-sync gcovr --filter=src --xml coverage_cpp.xml --merge-mode-functions=merge-use-line-min

      - uses: codecov/codecov-action@v7
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml,./coverage_cpp.xml

  test-pymmcore-plus:
    name: test pymmcore-plus ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    env:
      UV_NO_SYNC: "1"
    steps:
      - uses: actions/checkout@v7
        with:
          repository: pymmcore-plus/pymmcore-plus
      - uses: actions/checkout@v7
        with:
          path: pymmcore-nano
      - uses: astral-sh/setup-uv@v10.2.0
        with:
          python-version: "3.13"
          enable-cache: true
      - uses: TheMrMilchmann/setup-msvc-dev@v4
        if: matrix.os == 'windows-latest'
        with:
          arch: x64
      - name: Setup MM test adapters
        uses: pymmcore-plus/setup-mm-test-adapters@main
        with:
          version: 75
      - name: Install dependencies
        run: |
          uv sync --no-dev --group test
          uv pip install ./pymmcore-nano
          uv pip uninstall pymmcore
          uv pip list

      - run: uv run pytest -v --color=yes -W ignore
